internal static partial class CodeCleanupTestCatalog
{
    internal static IReadOnlyList<(string Name, Func<Task> Run)> All { get; } =
    [
        ("review persistence: overlay preparation keeps native chat when diagnostics fail", OverlayPreparationDiagnosticsAsync),
        ("review persistence: overlay sizing clamps large inputs before integer conversion", OverlaySizingOverflowAsync),
        ("review persistence: overlay state reads preserve formats and reject oversized files", OverlayStateBoundsAsync),
        ("review commands: disabled application and setup actions remain blocked until enabled", DisabledRelayCommandsAsync),
        (HomeRefreshTimerFailureTestName, HomeRefreshTimerFailureAsync),
        (PredictionClockTimerFailureTestName, PredictionClockTimerFailureAsync),
        ("review timers: completed debounce timers release their resources", CompletedDebounceTimerAsync),
        ("code cleanup: diagnostics cannot discard a shared Kick token rotation", KickRotationDiagnosticsAsync),
        ("code cleanup: diagnostics cannot poison retries after a failed Kick rotation", KickRotationFailureDiagnosticsAsync),
        ("code cleanup: diagnostics preserve Kick lookup failure caching and caller cancellation", KickLookupDiagnosticsAsync),
        ("code cleanup: diagnostics preserve Twitch validation failure retries", TwitchValidationDiagnosticsAsync),
        ("code cleanup: diagnostics cannot reject a validated Twitch client ID", TwitchClientMismatchDiagnosticsAsync),
        ("code cleanup: diagnostics cannot stop download notifications the queue or retries", DownloadQueueDiagnosticsAsync),
        ("code cleanup: diagnostics cannot fail video when an optional avatar is unavailable", DownloadAvatarDiagnosticsAsync),
        ("code cleanup: diagnostics cannot interrupt playback cancellation or failure cleanup", PlaybackCleanupDiagnosticsAsync),
        ("review integrity: playback stop releases event handles after source disposal fails", () => PlaybackSourceDisposalFailureAsync(disposeEngine: false)),
        ("review integrity: playback disposal releases its runtime and worker after source disposal fails", () => PlaybackSourceDisposalFailureAsync(disposeEngine: true)),
        ("review integrity: playback disposal releases its worker after cancellation callbacks fail", PlaybackWorkerCancellationFailureAsync),
        ("review integrity: failed playback diagnostics preserve the direct media fallback", PlaybackGatewayDiagnosticsAsync),
        ("review recovery: Twitch remote disconnect still reconnects after cancellation callbacks fail", () => TwitchRemoteDisconnectRecoveryAsync(true)),
        ("review recovery: Twitch remote disconnect still reconnects after prediction cleanup diagnostics fail", () => TwitchRemoteDisconnectRecoveryAsync(false)),
        ("review recovery: Kick remote disconnect still reconnects after cancellation callbacks fail", () => KickRemoteDisconnectRecoveryAsync(false)),
        ("review recovery: Kick remote disconnect still reconnects after cancellation diagnostics fail", () => KickRemoteDisconnectRecoveryAsync(true)),
        ("review recovery: queued Twitch disconnection drains before disposal finishes", () => ChatQueuedDisconnectDuringDisposalAsync(true)),
        ("review recovery: queued Kick disconnection drains before disposal finishes", () => ChatQueuedDisconnectDuringDisposalAsync(false)),
        ("review recovery: Twitch rate-limit retries release responses even when diagnostics fail", TwitchRateLimitDiagnosticsAsync),
        ("review recovery: Kick website HTTP errors still use fallback after diagnostics fail", () => KickWebsiteFallbackDiagnosticsAsync("status")),
        ("review recovery: Kick website timeouts still use fallback after diagnostics fail", () => KickWebsiteFallbackDiagnosticsAsync("timeout")),
        ("review recovery: Kick website read failures still use fallback after diagnostics fail", () => KickWebsiteFallbackDiagnosticsAsync("read")),
        ("review recovery: Kick website malformed payloads still use fallback after diagnostics fail", () => KickWebsiteFallbackDiagnosticsAsync("payload")),
        ("review recovery: Kick fallback rejects malformed payloads even when diagnostics fail", KickFallbackPayloadDiagnosticsAsync),
        ("code cleanup: Twitch messages must target the requested channel", TwitchMessageTargetsAsync),
        ("code cleanup: Twitch disconnect releases resources after a writer flush failure", TwitchDisconnectAfterFlushFailureAsync),
        ("code cleanup: chat disconnect releases resources after cancellation callbacks fail", ChatDisconnectAfterCancellationFailureAsync),
        ("code cleanup: prediction EventSub disposal releases resources after its worker fails", PredictionEventSubDisposalAfterWorkerFailureAsync),
        ("code cleanup: image loading accepts local files and HTTPS while rejecting network shares", ImageUriLoadingAsync),
        ("code cleanup: legacy unused settings do not reset current preferences", LegacyUnusedSettingsAsync),
        ("code cleanup: offline packages require local relative references for every media resource", OfflinePackageReferencesAsync),
        ("code cleanup: chat supervisor disposal drains and releases resources after cancellation fails", SupervisorCancellationFailureAsync),
        ("code cleanup: chat supervisor worker failures cannot skip client disconnection", SupervisorWorkerFailureAsync),
        ("code cleanup: prediction EventSub cancellation failures still drain the worker", EventSubCancellationFailureAsync),
        ("code cleanup: replacing debounced work survives a failed cancellation callback", DebounceCancellationFailureAsync),
        ("review scheduling: rejected debounce delays preserve previously scheduled work", RejectedDebounceDelayAsync),
        ("code cleanup: Twitch prediction cancellation cannot skip disconnection or request draining", PredictionCancellationFailureAsync),
        ("code cleanup: Twitch disposal cannot invert prediction request locks", PredictionDisposalLockOrderAsync),
        ("code cleanup: lifetime download cancellation survives failed callbacks and allows retry", DownloadCancellationCallbackFailureAsync),
        ("code cleanup: lifetime download cancellation invokes callbacks outside the library lock", DownloadCancellationLockAsync),
        ("code cleanup: lifetime download shutdown drains jobs after a cancellation callback fails", DownloadShutdownCallbackFailureAsync),
        ("code cleanup: lifetime clearing tab starts cancels every registration after callback failure", TabStartCancellationFailureAsync),
        ("code cleanup: lifetime Home shutdown survives callback failure and reentrant disposal", HomeShutdownCallbackFailureAsync),
        ("code cleanup: lifetime Home shutdown drains background work and releases resources after failures", HomeShutdownDrainFailureAsync),
        ("code cleanup: Home features finish browse navigation after a cancellation callback fails", BrowseNavigationCancellationFailureAsync),
        ("code cleanup: Home features allow reentrant browse cancellation outside state locks", BrowseCancellationReentryAsync),
        ("code cleanup: Home features ignore late viewer-count loads after shutdown", BrowseLateViewerCountsAsync),
        ("code cleanup: Home features release followed-channel subscriptions after cancellation fails", FollowedCancellationFailureAsync),
        ("review cleanup: Recent shutdown releases its timer and subscriptions after cancellation fails", RecentCancellationFailureAsync),
        ("review cleanup: repair proxy disposal publishes its task before session callbacks", RepairProxyDisposalReentryAsync),
        ("review cleanup: repair proxy drains requests after lifetime cancellation fails", RepairProxyCancellationFailureAsync),
        ("review cleanup: repair session closes clients after a cancellation callback fails", RepairSessionCancellationFailureAsync),
        ("review cleanup: repair proxy releases resources after a request worker fails", RepairProxyWorkerFailureAsync),
        ("review cleanup: repair proxy diagnostics cannot interrupt session ownership", RepairProxyDiagnosticsAsync),
        ("review cleanup: playback gateway diagnostics retain the repaired media source", RepairGatewayDiagnosticsAsync),
        ("review cleanup: playback gateway releases its owned HTTP client after proxy failure", RepairGatewayFailureCleanupAsync),
        ("review cleanup: concurrent playback gateway disposal waits for the same cleanup", RepairGatewayConcurrentDisposalAsync),
        ("code cleanup: lifetime view model main shutdown survives callback failure and reentrant disposal", MainShutdownCallbackFailureAsync),
        ("code cleanup: lifetime view model stream-tab shutdown survives callback failure and reentrant disposal", StreamTabShutdownCallbackFailureAsync),
        ("code cleanup: lifetime main shutdown drains children and tracked work after background failure", MainShutdownDrainFailureAsync),
        ("review robustness: native overlay shutdown survives callback failure and reentrant disposal", NativeOverlayShutdownCallbackFailureAsync),
        ("review robustness: native overlay startup cancellation permits reentrant state access", NativeOverlayStartupCancellationReentryAsync),
        ("review robustness: native overlay shutdown survives failed startup diagnostics", NativeOverlayShutdownDiagnosticsAsync),
        ("review robustness: native overlay animation cancellation releases retained state after callback failure", NativeOverlayAnimationCancellationFailureAsync),
        ("overlay cancellation: frame shutdown drains its writer after cancellation callbacks fail", FrameWriteShutdownCancellationFailureAsync),
        ("overlay cancellation: frame invalidation survives cancellation failure and writes its replacement", () => FrameWriteReplacementCancellationFailureAsync(false)),
        ("overlay cancellation: critical clear supersession survives cancellation failure and writes its replacement", () => FrameWriteReplacementCancellationFailureAsync(true)),
        ("overlay cancellation: event listener stop survives cancellation failure and allows restart", OverlayEventStopCancellationFailureAsync),
        ("overlay event lifecycle: disposal drains a stopped listener still dispatching an event", () => OverlayEventRetiredListenerAsync(false)),
        ("overlay event lifecycle: disposal drains a replaced listener still dispatching an event", () => OverlayEventRetiredListenerAsync(true)),
        ("overlay event lifecycle: cancellation reentry keeps the newest listener and retires every predecessor", OverlayEventStartReentryAsync),
        ("overlay event lifecycle: stopping drains admitted listeners without waiting for a reentrant restart", OverlayEventStopReentryAsync),
        ("overlay event lifecycle: a disposed host cannot start another listener", OverlayEventStartAfterDisposalAsync),
        ("overlay event lifecycle: a busy pipe retries when diagnostics fail", OverlayEventBusyDiagnosticsAsync),
        ("background cleanup: timeout diagnostics cannot interrupt bounded draining", () => BackgroundDrainDiagnosticFailureAsync(true)),
        ("background cleanup: failure diagnostics cannot interrupt draining", () => BackgroundDrainDiagnosticFailureAsync(false)),
        ("overlay cancellation: hiding seek previews detaches canceled work and clears images after callback failure", SeekPreviewHideCancellationFailureAsync),
        ("VOD resume robustness: delayed samples at double speed save and restore actual progress", () => VodResumeDelayedRateSampleAsync(false)),
        ("VOD resume robustness: delayed samples retain progress after slowing playback", () => VodResumeDelayedRateSampleAsync(true)),
        ("VOD resume robustness: delayed samples still reject progress beyond supported speeds", () => VodResumeDelayedRateSampleAsync(false, impossibleJump: true)),
        ("VOD resume robustness: failed read diagnostics allow playback without overwriting history", VodResumeReadDiagnosticsAsync),
        ("VOD resume robustness: failed capture diagnostics allow a later bookmark retry", () => VodResumeCaptureDiagnosticsAsync(false)),
        ("VOD resume robustness: failed completion diagnostics allow a later bookmark retry", () => VodResumeCaptureDiagnosticsAsync(true)),
        ("VOD resume robustness: failed save diagnostics cannot strand queued seeks", VodResumeSaveDiagnosticsAsync),
        ("replay preparation cleanup: failed cancellation still drains and releases the prepared source", () => ReplayPreparationCancellationFailureAsync(false)),
        ("replay preparation cleanup: failed source disposal still releases cancellation", () => ReplayPreparationCancellationFailureAsync(true)),
        ("replay preparation cleanup: a faulted worker is observed and releases cancellation", ReplayPreparationWorkerFailureAsync),
        ("review robustness: settings readers permit concurrent atomic replacement", () => SnapshotReplacementSharingAsync(false)),
        ("review robustness: VOD history readers permit concurrent atomic replacement", () => SnapshotReplacementSharingAsync(true)),
        ("review cleanup: settings readers retry a replacement file that is still exclusively open", () => SnapshotReplacementSharingAsync(false, exclusiveReplacement: true)),
        ("review cleanup: VOD history readers retry a replacement file that is still exclusively open", () => SnapshotReplacementSharingAsync(true, exclusiveReplacement: true)),
        ("review cleanup: settings replacement retries honor cancellation and allow a later read", () => SnapshotReplacementSharingAsync(false, exclusiveReplacement: true, cancelRead: true)),
        ("review cleanup: VOD history replacement retries honor cancellation and allow a later read", () => SnapshotReplacementSharingAsync(true, exclusiveReplacement: true, cancelRead: true)),
        ("review robustness: damaged VOD history recovery survives failed diagnostics", VodHistoryRecoveryDiagnosticsAsync),
        ("code cleanup: transport shutdown publishes its task before logging callbacks and drains output", () => TransportShutdownLogReentryAsync(false)),
        ("code cleanup: transport shutdown drains output and releases resources after logging fails", () => TransportShutdownLogReentryAsync(true)),
        ("code cleanup: release notes keep Updating headings inside valid fenced samples", ReleaseNotesFenceSplittingAsync),
        ("code cleanup: release notes render fenced samples as literal text", ReleaseNotesFenceRenderingAsync),
        ("code cleanup: release notes preserve blank lines and indentation in code samples", ReleaseNotesCodeWhitespaceAsync)
    ];

    private static Task TwitchMessageTargetsAsync()
    {
        const string prefix = "@display-name=Viewer :viewer!viewer@viewer.tmi.twitch.tv PRIVMSG ";
        foreach (var target in new[] { "#other", "viewer", "#streamer,#other", "#streamer extra", "#streamer-other", "#" })
        {
            Assert.Equal<ChatMessage?>(null, TwitchIrcParser.TryParsePrivMsg($"{prefix}{target} :hello", "streamer"));
        }

        var matching = TwitchIrcParser.TryParsePrivMsg($"{prefix}#STREAMER :hello", "streamer");
        Assert.NotNull(matching);
        Assert.Equal("streamer", matching!.Channel);
        Assert.Equal("hello", matching.Message);
        return Task.CompletedTask;
    }
}
