internal static class TestCatalog
{
    private const int CharacterizedTestCount = 703;

    internal static IReadOnlyList<(string Name, Func<Task> Run)> All { get; } = Build();

    private static IReadOnlyList<(string Name, Func<Task> Run)> Build()
    {
        (string Name, Func<Task> Run)[] characterized =
        [
            .. ApplicationTestCatalog.CoreAndInput,
            .. ApplicationTestCatalog.PlaybackBrowseAndReplay,
            .. ApplicationTestCatalog.OverlayRendering,
            .. ApplicationTestCatalog.ReplayAndLiveChat,
            .. ApplicationTestCatalog.ChatSettingsAndPredictions,
            .. ApplicationTestCatalog.TabsAndWindowing,
            .. ApplicationTestCatalog.HomeAndBrowseUi,
            .. ApplicationTestCatalog.WpfAndNativeWindows,
            .. TestSubsystemCatalog.All
        ];

        if (characterized.Length != CharacterizedTestCount)
        {
            throw new InvalidOperationException(
                $"The characterized test catalog must contain exactly {CharacterizedTestCount} tests; found {characterized.Length}.");
        }

        (string Name, Func<Task> Run)[] all =
            [
                .. characterized,
                .. LivePlaybackRecoveryTestCatalog.All,
                .. VodResumeTestCatalog.All,
                .. ApplicationTestCatalog.InactiveVodPlaybackTests,
                .. VodDownloadTestCatalog.All,
                .. VodDownloadTestCatalog.LiveProbeTests,
                .. ApplicationTestCatalog.VodDownloadUiTests,
                .. ApplicationTestCatalog.VodDownloadNativeTests,
                .. VodHistoryRegressionTestCatalog.All,
                .. HlsReplayTimelineTestCatalog.All,
                .. HlsDeltaPlaylistTestCatalog.All,
                .. ApplicationTestCatalog.LongVodReplayTests,
                .. ApplicationTestCatalog.VodSeekLatencyTests,
                .. ApplicationTestCatalog.LiveFirstSeekTests,
                .. ApplicationTestCatalog.ReplayPlaybackRateRecoveryTests,
                .. ApplicationTestCatalog.PlaybackRateControlTests,
                .. LiveFirstSeekRoutingTestCatalog.All,
                .. LiveReplayDemuxerTestCatalog.All,
                .. ApplicationTestCatalog.VodStartupNativeTests,
                .. ApplicationTestCatalog.FastVodResumeTests,
                .. ApplicationTestCatalog.ReplayColorTests,
                .. FastVodResumeTestCatalog.All,
                .. TwitchVodStartupTestCatalog.All,
                .. VodCompletionTestCatalog.All,
                .. VodChatRoutingTestCatalog.All,
                .. ApplicationTestCatalog.VodChatRoutingNativeTests,
                .. ApplicationTestCatalog.VodCompletionTests,
                .. VodWatchProgressTestCatalog.All,
                .. VodWatchedCompletionTestCatalog.All,
                .. ApplicationTestCatalog.VodWatchProgressTests,
                .. ApplicationTestCatalog.VodResumeNativeTests,
                .. ApplicationTestCatalog.OverlayReadabilityTests,
                .. ApplicationTestCatalog.ChatTextSizeTests,
                .. UpdateModernizationTestCatalog.RefreshTests,
                .. UpdateModernizationTestCatalog.ReleaseTests,
                .. UpdateModernizationTestCatalog.CleanupTests,
                .. UpdateModernizationTestCatalog.DependencyRecoveryTests,
                .. ApplicationTestCatalog.ReplaySeekOverlayTests,
                .. ApplicationTestCatalog.ResponsiveLayoutTests,
                .. ApplicationTestCatalog.StudioShellTests,
                .. ApplicationTestCatalog.StudioPolishTests,
                .. ApplicationTestCatalog.SettingsAutoSaveTests,
                .. ApplicationTestCatalog.StudioRefinementTests,
                .. ApplicationTestCatalog.SearchPopupDismissalTests,
                .. ApplicationTestCatalog.StudioExperienceTests,
                .. ApplicationTestCatalog.StudioDesignTests,
                .. ApplicationTestCatalog.TabSwitchVideoBoundsTests,
                .. ApplicationTestCatalog.TabContentInputTests,
                .. ApplicationTestCatalog.ResizeFlashTests,
                .. ApplicationTestCatalog.VolumeOverlaySizingTests,
                .. ApplicationTestCatalog.MainFullscreenEdgeTests,
                .. ApplicationTestCatalog.StreamBottomEdgeTests,
                .. ApplicationTestCatalog.PictureInPictureResizeTests,
                .. ApplicationTestCatalog.PictureInPictureResizeVlcTests,
                .. ApplicationTestCatalog.PictureInPictureActivationTests,
                .. ApplicationTestCatalog.PictureInPictureContextMenuTests,
                .. ApplicationTestCatalog.PictureInPictureContextMenuSurfaceTests,
                .. ApplicationTestCatalog.PictureInPictureContextMenuForeignForegroundTests,
                .. PictureInPictureContextMenuDispatchTestCatalog.All,
                .. NativePictureInPictureContextMenuTargetTestCatalog.All,
                .. AudioSwitchVlcTestCatalog.All,
                .. NeverMuteTabTestCatalog.All,
                .. BootstrapperTestCatalog.All,
                .. InstallerDependencyTestCatalog.All,
                .. MaintenanceTestCatalog.All,
                .. RegressionTestCatalog.All,
                .. CodeReviewTestCatalog.All,
                .. RepositoryAuditTestCatalog.All,
                .. ComprehensiveReviewTestCatalog.All,
                .. HttpLifecycleTestCatalog.All,
                .. ReviewFollowupTestCatalog.All,
                .. RepositoryReviewTestCatalog.All,
                .. KickUserTokenTestCatalog.All,
                .. PagingRegressionTestCatalog.All,
                .. VodChatLifecycleTestCatalog.All,
                .. GrowingVodChatTestCatalog.All,
                .. DvrChatSeekTransitionTestCatalog.All,
                .. ApplicationTestCatalog.ReplayChatAvailabilityTests,
                .. KickRecentChatTestCatalog.All,
                .. AppLifecycleTestCatalog.All,
                .. HotkeySettingsExpansionTestCatalog.All,
                .. MouseWheelDispatchTestCatalog.All,
                .. ApplicationTestCatalog.VolumeWheelInputTests,
                .. NativeMouseWheelTargetTestCatalog.All,
                .. PlaybackHotkeyIntegrationTestCatalog.All,
                .. ApplicationTestCatalog.SkipHotkeyTests,
                .. ApplicationTestCatalog.PauseHotkeyTests,
                .. ApplicationTestCatalog.BackHotkeyNativeVlcTests,
                .. ApplicationTestCatalog.WindowSharingVlcTests,
                .. ApplicationTestCatalog.NavigationTests,
                .. ApplicationTestCatalog.BrowseScrollTests,
                .. AnimatedEmoteDecodingTestCatalog.All,
                .. ProfileAvatarTestCatalog.All,
                .. ResourceUsageTestCatalog.All,
                .. OwnedProcessTestCatalog.All,
                .. MultistreamResourceTestCatalog.All,
                .. ApplicationTestCatalog.MultistreamUiResourceTests,
                .. MultistreamInitializationTestCatalog.All,
                .. ApplicationTestCatalog.MultistreamResourceBenchmarks,
                .. ApplicationTestCatalog.MultistreamLiveSmokeTests,
                .. WorkflowResourceTestCatalog.All,
                .. StreamOpenWorkflowTestCatalog.All,
                .. StartWatchWorkflowTestCatalog.All,
                .. ApplicationTestCatalog.StartWatchNativeTests,
                .. RecentRefreshResourceTestCatalog.All,
                .. ApplicationTestCatalog.RecentStreamNavigationTests,
                .. HomeRefreshResourceTestCatalog.All,
                .. BrowseStreamResourceTestCatalog.All,
                .. StreamHoverPreviewTestCatalog.All,
                .. ApplicationTestCatalog.StreamHoverPreviewUiTests,
                .. ApplicationTestCatalog.StreamHoverPreviewLiveUiTests,
                .. PagedRefreshResourceTestCatalog.All,
                .. BackgroundWorkflowResourceTestCatalog.All,
                .. ChatCatalogResourceTestCatalog.All,
                .. TwitchMutedVodRepairTestCatalog.All,
                .. PlaylistRedirectTestCatalog.All,
                .. TwitchChannelPointsTestCatalog.All,
                .. StreamSearchTestCatalog.All,
                .. ApplicationTestCatalog.VodLinkMetadataTests,
                .. ApplicationTestCatalog.LiveVodLinkMetadataTests,
                .. LiveChannelPayloadTestCatalog.All,
                .. SettingsRecoveryTestCatalog.All,
                .. TestRunnerValidationTestCatalog.All,
                .. NotificationIdentityTestCatalog.All,
                .. KickFollowImportTestCatalog.All,
                .. KickClipTestCatalog.All,
                .. ReviewContinuationTestCatalog.All,
                .. ServiceResilienceTestCatalog.All,
                .. ProfileImageLookupTestCatalog.All,
                .. ReplayChatResilienceTestCatalog.All,
                .. ApplicationTestCatalog.PauseSeekbarTests,
                .. ApplicationTestCatalog.ReplaySeekChatTimingTests,
                .. PollingLifecycleTestCatalog.All,
                .. TwitchPayloadValidationTestCatalog.All,
                .. TwitchCategoryViewerCountTestCatalog.All,
                .. TimeoutRecoveryTestCatalog.All,
                .. SeekPreviewResilienceTestCatalog.All,
                .. ReplayPromotionRaceTestCatalog.All,
                .. CommandLifetimeTestCatalog.All,
                .. ChatSendLifetimeTestCatalog.All,
                .. ChatCatalogLifecycleTestCatalog.All,
                .. OfflineFollowedChannelsTestCatalog.All,
                .. EmojiTitleTestCatalog.All,
                .. NativeInputFocusTestCatalog.All
            ];
        var duplicate = all
            .GroupBy(test => test.Name, StringComparer.Ordinal)
            .FirstOrDefault(group => group.Count() != 1);
        if (duplicate is not null)
        {
            throw new InvalidOperationException($"Test '{duplicate.Key}' is registered more than once.");
        }

        return all;
    }
}
